# Generated by Django 3.0.7 on 2020-12-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201226_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='google_link',
            new_name='twitter_link',
        ),
    ]
